name: FTP Deploy
run-name: Deploy MekBay to mekbay.com
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    name: Build and Upload
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2.3.2
      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install NPM and Build Angular Project
        run: |  
          npm install
          npm run build
      - name: Get LFTP
        run: sudo apt install lftp
      - name: Configure LFTP
        run: mkdir ~/.lftp && echo "set ssl:verify-certificate false;" >> ~/.lftp/rc
      - name: Load Secrets
        run: echo "machine ${{ secrets.FTP_HOST }} login ${{ secrets.FTP_USER }} password ${{ secrets.FTP_PASSWORD }}" > ~/.netrc
      - name: Upload Folder
        run: lftp -e "mirror --parallel=100 -R ./dist/browser ./mekbay/" ${{ secrets.FTP_HOST }}
